Repository AY2223S2-CS2103T-T09-2/tp, pull requests merged in 2023-03, with the labels that each got.

#41 Add Events and EventLists
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/IsolatedEvent.java
  src/main/java/seedu/address/model/event/IsolatedEventList.java
  src/main/java/seedu/address/model/event/PersonEventList.java
  src/main/java/seedu/address/model/event/RecurringEvent.java
  src/main/java/seedu/address/model/event/RecurringEventList.java
  src/test/java/seedu/address/model/event/IsolatedEventListTest.java
  src/test/java/seedu/address/model/event/RecurringEventListTest.java
Labels: v1.2

#37 Add Group, UniqueGroupList class and Group exceptions
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/group/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/model/group/exceptions/GroupNotFoundException.java
  src/main/java/seedu/address/model/group/exceptions/PersonAlreadyInGroupException.java
  src/main/java/seedu/address/model/group/exceptions/PersonNotInGroupException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedGroup.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/group/UniqueGroupListTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: v1.2

#46 Update group-related models
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/group/Group.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/group/GroupTest.java
  src/test/java/seedu/address/model/group/UniqueGroupListTest.java
Labels: v1.2

#38 Add command classes and command parser classes for group commands
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/group/GroupCommand.java
  src/main/java/seedu/address/logic/commands/group/GroupCreateCommand.java
  src/main/java/seedu/address/logic/commands/group/GroupDeleteCommand.java
  src/main/java/seedu/address/logic/commands/group/GroupFindCommand.java
  src/main/java/seedu/address/logic/commands/group/GroupListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserHelper.java
  src/main/java/seedu/address/logic/parser/group/GroupCommandParser.java
  src/main/java/seedu/address/logic/parser/group/GroupCreateCommandParser.java
  src/main/java/seedu/address/logic/parser/group/GroupDeleteCommandParser.java
  src/main/java/seedu/address/logic/parser/group/GroupFindCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/GroupNameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/group/UniqueGroupList.java
  src/main/java/seedu/address/model/person/MemberOfGroupPredicate.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/GroupCard.java
  src/main/java/seedu/address/ui/GroupListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/GroupListCard.fxml
  src/main/resources/view/GroupListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/group/GroupCreateCommandTest.java
  src/test/java/seedu/address/logic/commands/group/GroupDeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/group/GroupFindCommandTest.java
  src/test/java/seedu/address/logic/commands/group/GroupListCommandTest.java
  src/test/java/seedu/address/logic/parser/group/GroupCommandParserTest.java
  src/test/java/seedu/address/logic/parser/group/GroupCreateCommandParserTest.java
  src/test/java/seedu/address/logic/parser/group/GroupDeleteCommandParserTest.java
  src/test/java/seedu/address/logic/parser/group/GroupFindCommandParserTest.java
  src/test/java/seedu/address/model/person/MemberOfGroupPredicateTest.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: v1.2

#48 Add more Tests for Groups
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/group/GroupDeleteCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/group/exceptions/PersonAlreadyInGroupException.java
  src/main/java/seedu/address/model/group/exceptions/PersonNotInGroupException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/GroupListCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateGroupsAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/group/GroupFindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/testutil/TypicalGroups.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: v1.2

#62 Update Userguide
  docs/UserGuide.md
Labels: documentation

#59 Modify edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/group/exceptions/DuplicateGroupException.java
  src/main/java/seedu/address/model/group/exceptions/PersonAlreadyInGroupException.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/group/GroupCreateCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: v1.3

#66 Fix bug found for event
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddIsolatedEventCommand.java
  src/main/java/seedu/address/logic/commands/AddRecurringEventCommand.java
  src/main/java/seedu/address/logic/commands/EditIsolatedEventCommand.java
  src/main/java/seedu/address/logic/commands/EditRecurringEventCommand.java
  src/main/java/seedu/address/logic/parser/AddIsolatedEventCommandParser.java
  src/main/java/seedu/address/logic/parser/AddRecurringEventCommandParser.java
  src/main/java/seedu/address/logic/parser/EditIsolatedEventCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/IsolatedEvent.java
  src/main/java/seedu/address/model/event/RecurringEvent.java
  src/test/java/seedu/address/logic/commands/AddIsolatedEventCommandTest.java
  src/test/java/seedu/address/logic/commands/AddRecurringEventCommandTest.java
  src/test/java/seedu/address/model/event/IsolatedEventListTest.java
  src/test/java/seedu/address/model/event/IsolatedEventTest.java
  src/test/java/seedu/address/testutil/SampleDateTimeUtil.java
Labels: bug

#64 Update Userguide.md based on reviews and suggestions given
  docs/UserGuide.md
Labels: documentation

#68 Update events displayed on PersonCard
  src/main/java/seedu/address/model/AddressBook.java
Labels: bug

#67 Fixed Group bug
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug

#69 Fix bug for event list
  src/main/java/seedu/address/logic/commands/AddIsolatedEventCommand.java
  src/main/java/seedu/address/logic/commands/AddRecurringEventCommand.java
  src/main/java/seedu/address/logic/commands/EditIsolatedEventCommand.java
  src/main/java/seedu/address/logic/commands/EditRecurringEventCommand.java
  src/main/java/seedu/address/model/event/IsolatedEventList.java
  src/main/java/seedu/address/model/event/RecurringEvent.java
  src/main/java/seedu/address/model/event/RecurringEventList.java
  src/test/java/seedu/address/logic/commands/AddRecurringEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditIsolatedEventCommandTest.java
  src/test/java/seedu/address/logic/commands/EditRecurringEventCommandTest.java
Labels: bug

#70 Update index.md and Developer Guide
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/diagrams/GroupCreateCommandActivityDiagram.puml
  docs/diagrams/GroupCreateCommandSequenceDiagram.puml
  docs/diagrams/GroupDeleteCommandActivityDiagram.puml
  docs/diagrams/GroupDeleteCommandSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/EditCommandActivityDiagram.png
  docs/images/EditCommandSequenceDiagram.png
  docs/images/GroupCreateCommandActivityDiagram.png
  docs/images/GroupCreateCommandSequenceDiagram.png
  docs/images/GroupDeleteCommandActivityDiagram.png
  docs/images/GroupDeleteCommandSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/index.md
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: documentation

#72 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/EditCommandSequenceDiagram.puml
  docs/diagrams/GroupCreateCommandSequenceDiagram.puml
  docs/diagrams/GroupDeleteCommandSequenceDiagram.puml
  docs/diagrams/GroupFindCommandActivityDiagram.puml
  docs/diagrams/GroupFindCommandSequenceDiagram.puml
  docs/images/EditCommandSequenceDiagram.png
  docs/images/GroupCreateCommandSequenceDiagram.png
  docs/images/GroupDeleteCommandSequenceDiagram.png
  docs/images/GroupFindCommandActivityDiagram.png
  docs/images/GroupFindCommandSequenceDiagram.png
Labels: documentation

#74 Add Export features and test
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ExportCommandParser.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/ExportStorage.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonExportStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/ExportCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonExportStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: v1.3

#88 Finding free time slot feature
  README.md
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/gmengqi.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/FindTimeCommand.java
  src/main/java/seedu/address/logic/parser/FindTimeCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/IsolatedEvent.java
  src/main/java/seedu/address/model/event/RecurringEventList.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/timeslot/TimeMask.java
  src/main/java/seedu/address/model/timeslot/TimeSlot.java
  src/main/java/seedu/address/ui/TimeSlotCard.java
  src/main/java/seedu/address/ui/TimeSlotListPanel.java
  src/main/resources/view/TimeSlotListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/group/GroupCreateCommandTest.java
Labels: priority.High

#79 Fix bug where content overflows for both event list
  src/main/resources/view/PersonListCard.fxml
Labels: bug

#82 fix bug for edit isolated event command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditIsolatedEventCommand.java
  src/test/java/seedu/address/logic/commands/EditIsolatedEventCommandTest.java
Labels: bug

#102 Fixed timetable UI bug
  src/main/java/seedu/address/ui/WhereGotTimeTable.java
  src/main/resources/view/TimeSlotListCard.fxml
Labels: bug, v1.3

#99 Fix bug for isolated event
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditIsolatedEventCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/event/IsolatedEvent.java
  src/main/java/seedu/address/model/event/IsolatedEventList.java
  src/test/java/seedu/address/logic/commands/EditIsolatedEventCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/event/IsolatedEventListTest.java
Labels: bug

#108 Fix bug where day is not being compared
  src/main/java/seedu/address/model/event/RecurringEventList.java
Labels: bug

#115 Update Ui.png
  docs/images/Ui.png
Labels: v1.3
